#!/usr/bin/env bash

set -e

PS3='Please enter your choice: '
options=("Mac OS X" "Linux" "Install SPF-13 Vim" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Mac OS X")
            echo "Installing Mac dotfiles"
            CONFIG_RAW="MacOSX"
            BASE_INSTALL=1
            break
            ;;
        "Linux")
            echo "Installing Linux dotfiles"
            CONFIG_RAW="Linux"
            BASE_INSTALL=1
            break
            ;;
        "Install SPF-13 Vim")
            echo "Installing SPF-13 Vim."
            CONFIG_RAW="SPF-13"
            BASE_INSTALL=0
            break
            ;;
        "Quit")
            break
            ;;
        *) echo invalid option;;
    esac
done

if [ -n "$CONFIG_RAW" ]; then

  CONFIG="$CONFIG_RAW.conf.yaml"
  DOTBOT_DIR="dotbot"

  DOTBOT_BIN="bin/dotbot"
  BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

  cd "${BASEDIR}"
  git submodule update --init --recursive

  if [ $BASE_INSTALL -gt 0 ]; then
    echo "Installing common settings"
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "Common.conf.yaml" "${@}"
  fi

  echo "Running Dotbot using Config: $CONFIG"
  "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
fi
